[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''
on_i = 1

[[plugins]]
repo = 'davidhalter/jedi'
hook_add = '''
    hi Pmenu ctermbg=Gray
'''
on_ft = 'python'

# [[plugins]]
# repo = 'zchee/deoplete-jedi'
# hook_source = '''
# let g:deoplete#sources#jedi#server_timeout = 20
# '''
# on_ft = 'python'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
  '''
on_ft = ['json']
